repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [ '--line-length=100' ]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ '--profile=black' ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ '--remove-all-unused-imports', '--remove-unused-variables', '--in-place', '--recursive', '--exclude=__init__.py' ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [ '--max-line-length=100', '--max-complexity=10', '--extend-ignore=E265,E266,E266,E501' ]
