repos:
  # Pre-commit hooks provided by pre-commit-hooks repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Check YAML files for syntax errors
      - id: check-yaml
      # Ensure files end with a newline
      - id: end-of-file-fixer
      # Remove trailing whitespace from files
      - id: trailing-whitespace
      # Check for merge conflict markers in files
      - id: check-merge-conflict
      # Check JSON files for syntax errors
      - id: check-json
      # Check for large files added to the repository
      - id: check-added-large-files
        args: [ '--maxkb=50000000' ]  # Set maximum file size to 50MB

  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [ '--line-length=100' ]  # Set maximum line length to 100 characters

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ '--profile=black' ]  # Use the Black formatting profile for isort

  # Remove unused imports and variables with autoflake
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ '--remove-all-unused-imports', '--remove-unused-variables', '--in-place', '--recursive', '--exclude=__init__.py' ]  # Remove unused imports and variables

  # Static code analysis with Flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=100',  # Set maximum line length to 100 characters
          '--max-complexity=10',  # Set maximum complexity to 10
          '--extend-ignore=E265,E266,E266'  # Ignore specific errors E265, E266
        ]
